name: ExtremeParkour
main: net.yzimroni.extremeparkour.ExtremeParkourPlugin
version: 0.1
description: ExtremeParkour Plugin
authors: [yzimroni]
commands:
  parkour:
    description: ExtremeParkour command
    aliases: [p, eparkour, extremeparkour, ep]